[project]
name = "python-markdown-writer"
version = "0.1.0"
description = "Create Markdown documents from within your Python code."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "tabulate>=0.9.0",
]
