[project]
name = "markdown-writer"
version = "0.1.0"
description = "A simple Markdown writer for Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "tabulate>=0.9.0",
]
