[project]
name = "python-markdown-writer"
version = "0.2.1"
description = "Create Markdown documents from within your Python code."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.3",
    "tabulate>=0.9.0",
]
